apiVersion: tf.crossplane.io/v1alpha1
kind: Workspace
metadata:
  name: private-ai-eks
spec:
  forProvider:
    source: Remote
    module: git::https://github.com/nethopper2/cluster-bootstrapping.git//eks-module
  writeConnectionSecretToRef:
    namespace: default
    name: private-ai-eks-connection-ref
  providerConfigRef:
    name: awsconfig
