apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: awsconfig-dan
spec:
  credentials:
    - filename: aws-creds-dan.ini
    - secretRef:
        key: creds
        name: aws-creds-dan
        namespace: default
      source: Secret