apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: awsconfig-dan
spec:
  credentials:
    - secretRef:
        key: creds
        name: aws-creds-dan
        namespace: default
      filename: aws-creds-dan.ini
      source: Secret