apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: awsconfig-mike
spec:
  credentials:
    filename: aws-creds-mike.ini
    - secretRef:
        key: creds
        name: aws-creds
        namespace: default
      source: Secret
