apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: mike-vpc
spec:
  forProvider:
    source: Remote
    module: git::https://github.com/nethopper2/cluster-bootstrapping.git//vpc-module
  writeConnectionSecretToRef:
    namespace: default
    name: mike-vpc
  providerConfigRef:
    name: awsconfig-mike
