apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: dan-vpc
spec:
  forProvider:
    source: Remote
    module: git::https://github.com/nethopper2/cluster-bootstrapping.git//vpc-module-dan
  writeConnectionSecretToRef:
    namespace: default
    name: dan-vpc
  providerConfigRef:
    name: awsconfig-dan
